### ISSUE TITLE
Add supports for MSH.9.3 Message Structure

### ISSUE THREAD

**Issue by alexandre-le-borgne** [senaranya/HL7#108]
Thank you for sharing this implementation

As described here : https://hl7-definition.caristix.com/v2/HL7v2.5/Fields/MSH.9

I expected to see the following 3 elements in the MSH : 

- MSH.9.1 - Message Code
- MSH.9.2 - Trigger Event
- MSH.9.3 - Message Structure

But apparently the lib only natively supports message code "aka messageType" and trigger event.

For now I'm using this workaround :

```php
$req = HL7::from("my hprim")->createMessage();

/** @var HL7\Segments\MSH $msh */
$msh = $req->getSegmentByIndex(0);

$ack = new HL7\Messages\ACK(
    $req,
    $msh,
    [
        'HL7_VERSION' => '2.5',
    ]
);

/** @var HL7\Segments\MSH $ackMsh */
$ackMsh = $ack->getSegmentByIndex(0);

$ackMshMessageType = ['ACK', $msh->getTriggerEvent(), 'ACK'];
$ackMsh->setField(9, $ackMshMessageType);

echo $ack->toString(true);        
```

**Comment by senaranya** [comment]
I'll work on this as soon as I can. Thanks for raising this issue

**Comment by senaranya** [comment]
I've added a PR #109 with the change. Can you check if that's going to work for you?

**Comment by alexandre-le-borgne** [comment]
Oh thank you for being so efficient. I'll try and let you know (probably Tuesday)

**Comment by alexandre-le-borgne** [comment]
it works, except for the warning on the type of the argument

![image](https://github.com/senaranya/HL7/assets/10196942/cb5276e3-6ce5-4e22-a337-c0d52d782cc2)

**Comment by senaranya** [comment]
Try again please, I've pushed a fix in the phpdoc
