### ISSUE TITLE
How to parse a hl7 data 

### ISSUE THREAD

**Issue by coolSumanta** [senaranya/HL7#16]
I am getting a mixed array or we can say associative array if I am not wrong . i want the results be like this site https://hl7messageparser.azurewebsites.net/Parse/ParseView . Let me know is it possible to do the same .

**Comment by senaranya** [comment]
If you mean if it's possible to generate a tree structure, yes it is. You
can run a loop over each segment (use $msgObj->getSegments() to get array
of all segments), and an inner loop over all fields of each segment (using
$segment->getFields()) to create the tree according to your requirement.

Thanks,
Aranya.

**Comment by coolSumanta** [comment]
Can you be more specific? I want the structure like can you please help me
out .
Regards ,
Sumanta Mukhopadhyay

**Comment by coolSumanta** [comment]
`$msg = new Message("MSH|^~\&|ADT1|MCM|LABADT|MCM|198808181126|SECURITY|ADT^A01|MSG00001-|P|2.6 EVN|A01|198808181123
        PID|||PATID1234^5^M11^^AN||JONES^WILLIAM^A^III||19610615|M||2106-3|677 DELAWARE AVENUE^^EVERETT^MA^02149|GL|(919)379-1212|(919)271-3434~(919)277-3114||S||PATID12345001^2^M10^^ACSN|123456789|9-87654^NC
        NK1|1|JONES^BARBARA^K|SPO|||||20011105
        NK1|1|JONES^MICHAEL^A|FTH
        PV1|1|I|2000^2012^01||||004777^LEBAUER^SIDNEY^J.|||SUR||-||ADM|A0
        AL1|1||^PENICILLIN||CODE16~CODE17~CODE18
        AL1|2||^CAT DANDER||CODE257
        DG1|001|I9|1550|MAL NEO LIVER, PRIMARY|19880501103005|F
        PR1|2234|M11|111^CODE151|COMMON PROCEDURES|198809081123
        ROL|45^RECORDER^ROLE MASTER LIST|AD|RO|KATE^SMITH^ELLEN|199505011201
        GT1|1122|1519|BILL^GATES^A
        IN1|001|A357|1234|BCMD|||||132987
        IN2|ID1551001|123456789
        ROL|45^RECORDER^ROLE MASTER LIST|AD|RO|KATE^ELLEN|199505011201", null, true); // Either \n or \r can be used as segment endings
        $dataArrays =  $msg->getSegments();
        $dataset = [];
        foreach ($dataArrays as $data) {
            $dataset = $data->getFields();
            dump($dataset);
            if($dataset[0]==="MSH"){
                dd("true",$dataset);
            }
        }`

I made this getting values , but I want the tree to be more specific.
Regards ,
Sumanta Mukhopadhyay

**Comment by senaranya** [comment]
You seem to be on the right track. You can use an inner foreach loop like
this: foreach ($segment->getFields() as $field)
Inside the inner loop you can add the field to a multi-dimensional array,
e.g. $tree[$segment->getName()][] = $field

Thanks,
Aranya.

**Comment by coolSumanta** [comment]
the thing is I am getting it like you did string to array conversion with delimiter . Basically how will I know this is the address and this is the dob I have to guess it or what or do you have something for this .

**Comment by senaranya** [comment]
There is nothing in the library that detects/validates address, name, dob
etc. That has to be done in the application code. The library just helps
you get/set/add/remove/manage fields and segments, irrespective of data
content

Thanks,
Aranya.
