### ISSUE TITLE
Support (or ideas) on receiving HL7 from a remote host?

### ISSUE THREAD

**Issue by sburkett** [senaranya/HL7#17]
Hi all. This package works great for creating and sending stuff to a remote MLLP server, but is there any plan for adding support (or any ideas) for receiving HL7 data via a "always on" TCP stream?

I've tried using `socat` and other approaches, but I've not yet arrived at the right solution.

Thanks in advance!

**Comment by senaranya** [comment]
You can write a plain [TCP socket server](https://www.php.net/manual/en/sockets.examples.php) and add a [Supervisor](http://supervisord.org/) config to run it as a demon. 

I myself have been using the great [hl7d toolkit](http://hl7toolkit.sourceforge.net/#hl7d) for a while, but it has aged and hasn't been updated for a while. Hl7d toolkit can do its own parsing, but I'm using it just to receive HL7 stream and simply delegate it to my php suite for further processing. The same could probably be done using a simple TCP socket server script, but I've been too lazy to write one!

I had started adding a demon in this library, but faced a few minor challenges and stopped midway. I may take this up again later, or if someone else is interested in contributing, I couldn't be happier!

**Comment by sburkett** [comment]
True. All of my experience with creating my own socket servers has been around transaction based things. Customer connects, sends data, we save it, and then close the connection. The connection wasn't always open through the VPN to the customer with streaming data. But yes, I do think you are right. I may end up having to do that in this case.
