### ISSUE TITLE
Repetition

### ISSUE THREAD

**Issue by bdocky** [senaranya/HL7#20]
Hi,
how about adding this code to Message.php on line 120 to get repetition parsed?

if(stripos($fields[$j],$this->repetitionSeparator)==false) {
  $comps = preg_split("/\\" . $this->componentSeparator . '/', $fields[$j], -1, $preg_flags);
  foreach ($comps as $k => $kValue) {
     $subComps = preg_split("/\\" . $this->subcomponentSeparator . '/', $comps[$k]);
     (\count($subComps) === 1) ? ($comps[$k] = $subComps[0]) : ($comps[$k] = $subComps);
  }
  (\count($comps) === 1) ? ($fields[$j] = $comps[0]) : ($fields[$j] = $comps);
} else {
  $repets = preg_split("/\\" . $this->repetitionSeparator . '/', $fields[$j], -1, 0);
  $compsr=[];
  foreach ($repets as $rValue) {
     $comps = preg_split("/\\" . $this->componentSeparator . '/', $rValue, -1, $preg_flags);
     foreach ($comps as $k => $kValue) {
	$subComps = preg_split("/\\" . $this->subcomponentSeparator . '/', $comps[$k]);
	(\count($subComps) === 1) ? ($comps[$k] = $subComps[0]) : ($comps[$k] = $subComps);
    }
   (\count($comps) === 1) ? ($compsr[] = $comps[0]) : ($compsr[] = $comps);
  }
  $fields[$j] = $compsr;
}

**Comment by senaranya** [comment]
Can you please give me an example of a repetition and what should be the parsed value?

**Comment by bdocky** [comment]
Hai,
In this example the patient has two different addresses in the PID (Patient Identification) segment.

MSH|^~\&|hl7Integration|hl7Integration|||||ADT^A01|||2.3
EVN|A01|20130617154644
PID|1|465 306 5961||407623|Wood^Patrick^^^MR||19700101|1|||13 Oxford Road^^Oxford~16 London Road^^London
PV1|1||Location||||||||||||||||261938_6_201306171546|||||||||||||||||||||||||20130617134644

PID11 should be an array of array.
 [11] => Array
                                (
                                    [0] => Array
                                        (
                                            [0] => 13 Oxford Road
                                            [1] => 
                                            [2] => Oxford
                                        )

                                    [1] => Array
                                        (
                                            [0] => 16 London Road
                                            [1] => 
                                            [2] => London
                                        )

                                )

Bassam

**Comment by senaranya** [comment]
Looks great! Would you mind making some minor adjustments before I can merge? I have refactored the original snippet (that's now under `if` construct) into a method `extractComponentsFromFields()`. Can you please rebase/merge your branch with master and update the else part accordingly? Feel free to make any change in `extractComponentsFromFields()`, if required.

Also, it'll be great if you please add unit tests in MessageTest.php to cover the logic you've added. Since this is a core area of the engine, we'll need robust test coverage.

**Comment by senaranya** [comment]
Closing, as this is duplicated by #35
