### ISSUE TITLE
Authentication in headers

### ISSUE THREAD

**Issue by Lex-talionis** [senaranya/HL7#31]
Hi i'm probably missing something simple here but i can not set Auth headers for my connection. I don't see it in your docs either could you point me in  the right direction please.

**Comment by senaranya** [comment]
By auth header I'm guessing you mean HTTP auth? The connector class in this library just provides a simple TCP/IP connection. If you want to send HL7 over HTTP with auth, you'll have to use your own sender (using Guzzle/PHP Curl etc.)

**Comment by Lex-talionis** [comment]
Hi that's correct i thought as much and have done so. thanks for your quick response really handy bit of software btw great work and ty.
