### ISSUE TITLE
Socket validation issue on PHP 8

### ISSUE THREAD

**Issue by sakinobashi** [senaranya/HL7#41]
Hello,

I was getting the following error when attempting to create a new Connection on PHP 8:
````
Aranyasen\Exceptions\HL7ConnectionException with message 'Failed to create socket: Success'
````
After looking into it, I've found that it's because sockets have been moved from resources to objects, so the `if` on `Connection:72` has to be changed from:
````
if (!$socket || !is_resource($socket))
````
To:
````
if (!$socket || !(is_resource($socket) || $socket instanceof \Socket))
````
I'd submit a PR myself, but to be honest I've never done it before and I'm not sure I'd do it correctly.

Best regards!

Edit: according to https://php.watch/versions/8.0/sockets-sockets-addressinfo changing `is_resource($socket)` to `$socket !== false` also works, so I guess changing the if statement to just `if (!$socket)` would also work…?

**Comment by senaranya** [comment]
Thank you for reporting this. Support for PHP 8.0 is now added in release 2.0.3
