### ISSUE TITLE
I need help

### ISSUE THREAD

**Issue by eanzuresb** [senaranya/HL7#53]
I already install from composer, and I try to test, but i get this error in console:
crbug/1173575, non-JS module files deprecated.

My php versión is 7.3.24 

this is my code:
`<?php

// First, import classes from the library as needed...
use Aranyasen\HL7\Message; // If Message is used
use Aranyasen\HL7\Segment; // If Segment is used
use Aranyasen\HL7\Segments\MSH; // If MSH is used
// ... and so on

// Create a Message object from a HL7 string
$msg = new Message("MSH|^~\\&|1|\rPID|||abcd|\r"); // Either \n or \r can be used as segment endings
$pid = $msg->getSegmentByIndex(1);
echo $pid->getField(3); // prints 'abcd'
echo $msg->toString(true); // Prints entire HL7 string

// Get the first segment
$msg->getFirstSegmentInstance('PID'); // Returns the first PID segment. Same as $msg->getSegmentsByName('PID')[0];

// Check if a segment is present in the message object
$msg->hasSegment('PID'); // return true or false based on whether PID is present in the $msg object

// Check if a message is empty
$msg = new Message();
$msg->isempty(); // Returns true

?>
`

Thanks!

**Comment by senaranya** [comment]
This is a front-end issue, and not related to this library. A quick Google search says it might be a problem with Chrome/Angular, but could be something else as well
