### ISSUE TITLE
Split connection and message parts and make ext-sockets as non-required for install

### ISSUE THREAD

**Issue by dmtux** [senaranya/HL7#54]
In some cases, someone can use the package just for the as message creation framework and not going to handle socket connections maybe it would be worth removing ext-sockets from the requirements in composer.json and describe in README that it is required to install to run connection.

https://github.com/senaranya/HL7/blob/master/composer.json#L18

**Comment by senaranya** [comment]
Makes sense! Would you like to create a PR, or let me handle it?

**Comment by dmtux** [comment]
Not sure if would be able to make PR these days a bit busy with full-time responsibilities but at the same time don't want to push you. It is OpenSource you already did a great job :)
But in case if I will jump in just Scopes is: move ext-socket to require-dev, update README.md, make additional friendly exception handling in the Connection scope?

**Comment by dmtux** [comment]
@senaranya Please check https://github.com/senaranya/HL7/issues/54
