### ISSUE TITLE
toString method remove spacea between sections

### ISSUE THREAD

**Issue by franciscoolmfdz** [senaranya/HL7#9]
This error was discovered when i create a new message using the method " new Message",
creating a new object  from a string hl7 message format and next sending this message using a new connection  using connection->send(Message).

**Example** :
      $msjSend =new Message("MSH|^~\&|HL7Soup|Instance1|||||ADT^A04|1817457|D|2.5.1|123456||AL
PID||0797675^^^^MR|454721||Brown^Sam^^^^^B|Smith^Mary^^^^|19780203|M||2106-3|254 East St^^Howick^OH^3252^USA||(216)671-4859|||S|AGN|400003603~1629086|999-8888|
NK1||Brown^Mary^^^^|MTH||(216)891-3459||EC|||||||||||||||||||||||||||
PV1||O|O/R|A|||060277^Allen^Katrina^J^^^|||||||||| ||2668684|||||||||||||||||||||||||201407271408|");
        $connection = new Connection($ip,$port); 
        $response   = $connection->send($msjSend);
 
**Receive:**
"MSH|^~\&|HL7Soup|Instance1|ADT^A04|1817457|D|2.5.1|123456|AL
PID|0797675^MR|454721|Brown^Sam^B|Smith^Mary|19780203|M|21060101000000-3|254 East St^^Howick^OH^3252^USA||(216)671-4859|S|AGN|400003603~1629086|999-8888
NK1|Brown^Mary^|MTH|(216)891-3459|EC
PV1|O|O/R|A|060277^Allen^Katrina^J^|2668684|201407271408"

**Comment by senaranya** [comment]
Thank you for reporting this. I'm not able to understand from the example where it removed space. Can you please point it out?

**Comment by franciscoolmfdz** [comment]
ok, for example, if u have  simple message  with values in the sections "|"  1.1 and 5.1, and  next you send that message you receive the values in the section 1.1 and 2.1     removing the "|" between
 msj send example in hl7  msh|A||||B    
msj receive in hl7   msh|A|B  
 and that the problem, the message change and the origin value B are in wrong section

**Comment by senaranya** [comment]
You can add a "true" as a third argument to the Message() instantiation: ``new Message($string, null, true);``

**Comment by franciscoolmfdz** [comment]
works fine, thanks
